version: '3'
services:
  web:
    build: ./
    volumes:
    - ./:/var/www/shopee
    ports:
    - 3000:3000
    command:
      sh -c 'node bin/www'
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: shopee
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: shopee
      MYSQL_PASSWORD: shopee
