version: '2'
services:
  web:
    build: ./
    volumes:
    - ./:/var/www/app
    ports:
    - 3000:3000
    environment:
    - NODE_ENV=development
    - PORT=3000
    command:
      sh -c 'SET DEBUG=new:* & npm start'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
